/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MultipartFieldInfo {
  name?: string
  filename?: string
  contentType?: string
}
export declare class MultipartFileHandle {
  readChunk(size: number): Buffer | null
}
export declare class MultipartParserWrapper {
  constructor(contentType: string)
  feed(chunk: Buffer): void
  end(): void
  getNextFileInfo(): MultipartFieldInfo | null
  startReadingBody(): MultipartFileHandle | null
  moveToNextPart(): void
}
