/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MultipartFile {
  name?: string
  filename?: string
  contentType?: string
  stream(): ReadableStream<Buffer>
}
export declare class Multipart {
  constructor(stream: ReadableStream<Uint8Array>, contentType: string)
  next(callback: ((arg: MultipartFile) => Promise<undefined>)): Promise<void>
}
