/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MultipartField {
  name?: string
  data: Buffer
  filename?: string
  contentType?: string
}
export declare function getParts(contentType: string, body: Buffer): Array<MultipartField>
